services:
  db:
    container_name: s_db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       secret_service
    ports:
      - "5432:5432"            
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
